package org.hisand.bible;

public class Test {

	String[] indexs = new String[]{
"Gen_1.html,创世记,Genesis,50",
"Exo_1.html,出埃及记,Exodus,40",
"Lev_1.html,利未记,Leviticus,27",
"Num_1.html,民数记,Numbers,36",
"Deu_1.html,申命记,Deuteronomy,34",
"Jos_1.html,约书亚记,Joshua,24",
"Jug_1.html,士师记,Judges,21",
"Rut_1.html,路得记,Ruth,4",
"1Sa_1.html,撒母耳记上,1 Samuel,31",
"2Sa_1.html,撒母耳记下,2 Samuel,24",
"1Ki_1.html,列王记上,1 Kings,22",
"2Ki_1.html,列王记下,2 Kings,25",
"1Ch_1.html,历代记上,1 Chronicles,29",
"2Ch_1.html,历代记下,2 Chronicles,36",
"Ezr_1.html,以斯拉记,Ezra,10",
"Neh_1.html,尼希米记,Nehemiah,13",
"Est_1.html,以斯帖记,Esther,10",
"Job_1.html,约伯记,Job,42",
"Psm_1.html,诗篇,Psalms,150",
"Pro_1.html,箴言,Proverbs,31",
"Ecc_1.html,传道书,Ecclesiastes,12",
"Son_1.html,雅歌,Song of Songs,8",
"Isa_1.html,以赛亚书,Isaiah,66",
"Jer_1.html,耶利米书,Jeremiah,52",
"Lam_1.html,耶利米哀歌,Lamentations,5",
"Eze_1.html,以西结书,Ezekiel,48",
"Dan_1.html,但以理书,Daniel,12",
"Hos_1.html,何西阿书,Hosea,14",
"Joe_1.html,约珥书,Joel,3",
"Amo_1.html,阿摩司书,Amos,9",
"Oba_1.html,俄巴底亚书,Obadiah,1",
"Jon_1.html,约拿书,Jonah,4",
"Mic_1.html,弥迦书,Micah,7",
"Nah_1.html,那鸿书,Nahum,3",
"Hab_1.html,哈巴谷书,Habakkuk,3",
"Zep_1.html,西番雅书,Zephaniah,3",
"Hag_1.html,哈该书,Haggai,2",
"Zec_1.html,撒迦利亚书,Zechariah,14",
"Mal_1.html,玛拉基书,Malachi,4",
"Mat_1.html,马太福音,Matthew,28",
"Mak_1.html,马可福音,Mark,16",
"Luk_1.html,路加福音,Luke,24",
"Jhn_1.html,约翰福音,John,21",
"Act_1.html,使徒行传,Acts,28",
"Rom_1.html,罗马书,Romans,16",
"1Co_1.html,哥林多前书,1 Corinthians,16",
"2Co_1.html,哥林多后书,2 Corinthians,13",
"Gal_1.html,加拉太书,Galatians,6",
"Eph_1.html,以弗所书,Ephesians,6",
"Phl_1.html,腓立比书,Philippians,4",
"Col_1.html,歌罗西书,Colossians,4",
"1Ts_1.html,帖撒罗尼迦前书,1 Thessalonians,5",
"2Ts_1.html,帖撒罗尼迦后书,2 Thessalonians,3",
"1Ti_1.html,提摩太前书,1 Timothy,6",
"2Ti_1.html,提摩太后书,2 Timothy,4",
"Tit_1.html,提多书,Titus,3",
"Phm_1.html,腓利门书,Philemon,1",
"Heb_1.html,希伯来书,Hebrews,13",
"Jas_1.html,雅各书,James,5",
"1Pe_1.html,彼得前书,1Peter,5",
"2Pe_1.html,彼得后书,2Peter,3",
"1Jn_1.html,约翰一书,1 John,5",
"2Jn_1.html,约翰二书,2 John,1",
"3Jn_1.html,约翰三书,3 John,1",
"Jud_1.html,犹大书,Jude,1",
"Rev_1.html,启示录,Revelation,22"};

}
